id: 4a0d626164394072be785cbd88f8649c
initial_creation_type: ocr
source_metadata:
  volumes:
    08a464b8c46a438f8448b26d9584e645:
      base_file: v076.txt
      image_group_id: I1PD95922
      title: རྣམ་པར་བཤད་པ་རིགས་པའི་མདོ་སྡེའི་དུམ་བུ་བརྒྱ།
      total_pages: 1517
      volume_number: 77
